### ISSUE TITLE
Consider embedding the device tree and emulator into blockram

### ISSUE THREAD

**Issue by mithro** [skiphansen/panog2_linux#1]
With the Pano logic having such a *giant* FPGA. It probably makes a lot of sense to embed the device tree and emulator into the gateware rather than consuming extra SPI flash space.
```
0x410000 -> 0x413fff	0x0	device tree	1703
0x414000 -> 0x43ffff	0x4000	emulator	2992
```

**Comment by skiphansen** [comment]
This really is unusable flash space anyway if the goal is to be able to flash the gateware, Linux kernel and root file system independently.   I'm planning doing some Linux user land development and flashing *JUST* the root file system is essential for programmer sanity (it take about 5 minutes to flash the entire image).

Currently as I understand it the device tree is generated automatic by the gateware build based on the gateware configuration so it is unlikely to change independently of the gateware.  If the emulator is changed then the gateware/device/tree partition would have to be reflashed, but the bit file would not have to be regenerated.
